client_id = "41d1d7fae24939000bdbd2935ae8857f"
name = "Warranty Registration"
application_url = "https://geepas-warranty.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks/customers/update"
  include_fields = [ "tags", "phone", "first_name", "id" ]

[access_scopes]
scopes = "read_customers,read_metaobject_definitions,read_metaobjects,read_products,write_customers,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [ "https://geepas-warranty.vercel.app/auth/callback" ]